-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

	NDefines.NGame.END_DATE = "1900.1.10"
	NDefines.NCountry.HRE_MAX_RANK = 2
	NDefines.NCountry.FREE_IDEA_GROUP_COST = 4
	NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_STABILITY_COST = 0
	NDefines.NDiplomacy.IMPERIAL_AUTHORITY_FROM_PRINCES = 0.050
	NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STABILITY = 0.35
	NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_STATE_WITH_PROSPERITY = 0.05
	NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_TRIBUTARY_DEV = 0.15
	NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_COST = 50
